call plug#begin('~/.vim/plugged')

Plug 'chriskempson/base16-vim'
Plug 'scrooloose/syntastic'
Plug 'valloric/youcompleteme', {'do': './install.py --clang-completer'}

call plug#end()

filetype on 
syntax on                           "Syntax highlighting based on file names

colorscheme base16-monokai
let base16colorspace=256            "Access colors present in 256 colorspace
set background=dark

set guifont=Monaco\ 12              "Setting the font

set number
set lines=63 columns=90
set colorcolumn=90
